apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vla-eval
resources:
  - ../../base
  - secret.yaml
patches:
  - path: patch-config.yaml
images:
  - name: ghcr.io/haarikaalla/vlaeval-api
    newTag: latest
  - name: ghcr.io/haarikaalla/vlaeval-worker
    newTag: latest
  - name: ghcr.io/haarikaalla/vlaeval-frontend
    newTag: latest
  - name: ghcr.io/haarikaalla/vlaeval-mlflow
    newTag: latest
